# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import rc_pb2 as rc__pb2


class MsgCommStub(object):
    """Services to send gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRICControlReqServiceGrpc = channel.unary_unary(
                '/rc.MsgComm/SendRICControlReqServiceGrpc',
                request_serializer=rc__pb2.RicControlGrpcReq.SerializeToString,
                response_deserializer=rc__pb2.RicControlGrpcRsp.FromString,
                )


class MsgCommServicer(object):
    """Services to send gRPC
    """

    def SendRICControlReqServiceGrpc(self, request, context):
        """gRPC call to Send RICControlReqServiceGrpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgCommServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRICControlReqServiceGrpc': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRICControlReqServiceGrpc,
                    request_deserializer=rc__pb2.RicControlGrpcReq.FromString,
                    response_serializer=rc__pb2.RicControlGrpcRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rc.MsgComm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MsgComm(object):
    """Services to send gRPC
    """

    @staticmethod
    def SendRICControlReqServiceGrpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rc.MsgComm/SendRICControlReqServiceGrpc',
            rc__pb2.RicControlGrpcReq.SerializeToString,
            rc__pb2.RicControlGrpcRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
